name: Github CI
on:
  push:
    branches:
      - main
    tags:
      - '0.*.*'
      - '0.*'
  workflow_dispatch:

jobs:
  mingw:
    name: mingw
    runs-on: windows-latest
    env:
      MSYS2_DIR: msys64
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      ARCH: win64
      PLATFORM: x64

    steps:
    - name: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        path-type: minimal
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-libtool
          mingw-w64-x86_64-libiconv
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-swig
          mingw-w64-x86_64-python3
          libtool
          autoconf-wrapper
          automake-wrapper
          texinfo
          gperf
          mingw-w64-x86_64-perl
          mingw-w64-x86_64-pcre2

    - run: reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting" /f /v DontShowUI /d 1
    - run: swig -version
