name: Github CI
on:
  push:
    branches:
      - main
    tags:
      - '0.*.*'
      - '0.*'
  workflow_dispatch:

jobs:
  mingw:
    name: mingw
    runs-on: windows-latest
    env:
      MSYS2_DIR: msys64
      MSYS2_ARCH: x86_64
      MSYSTEM: MINGW64
      ARCH: win64
      PLATFORM: x64

    steps:
    - name: setup-msys2
      uses: msys2/setup-msys2@v2
      with:
        path-type: minimal
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-libtool
          mingw-w64-x86_64-libiconv
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-swig
          mingw-w64-x86_64-python3
          python-pip
          libtool
          autoconf-wrapper
          automake-wrapper
          texinfo
          gperf
          mingw-w64-x86_64-perl
          mingw-w64-x86_64-pcre2

    - run: reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting" /f /v DontShowUI /d 1

    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Cache build files
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache
          ./build
        key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - shell: msys2 {0}
      run: sh ./autogen.sh
      continue-on-error: true

    - shell: msys2 {0}
      run: ./configure --disable-dependency-tracking --enable-check-less

    - shell: msys2 {0}
      run: |
        export BUILD_DIR=build
        make -j

    - if: failure()
      shell: msys2 {0}
      run: make -C src dwg_api.i; tar cfz mingw-failure.tgz src/dwg_api.i src/config.h

    - if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: mingw-failure.tgz
        path: mingw-failure.tgz
    - shell: msys2 {0}
      run: |
        which python
        python --version
        which pip
        pip --version
    - shell: msys2 {0}
      run: /mingw64/bin/pip install --upgrade setuptools
      

    - shell: msys2 {0}
      run: python setup.py install

    - name: Test Python Binding
      shell: msys2 {0}
      run: |
        python -c "import sys; print(sys.path)"
        python -c "import libredwg; print('libredwg imported successfully')"
