name: Build LibreDWG with MinGW and Ninja

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install MinGW and Ninja
      run: |
        choco install mingw --no-progress
        choco install ninja --no-progress

    - name: Add MinGW to PATH
      run: |
        echo "C:\tools\mingw64\bin" >> $GITHUB_PATH

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress
      
    - name: Check MinGW Installation
      run: |
        gcc --version
        g++ --version
        ninja --version

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=C:\libredwg_install

    - name: Build Project
      run: |
        cd build
        cmake --build . --config Release

    - name: Package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: libredwg
        path: build
