name: Build LibreDWG with Python Bindings

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-dev swig autoconf libtool pkg-config

      - name: Run autogen.sh
        run: |
          ./autogen.sh

      - name: Configure and compile LibreDWG
        run: |
          ./configure
          make

      - name: Install LibreDWG
        run: |
          sudo make install

      - name: Generate Python bindings using SWIG
        run: |
          swig -python -outdir . -o libdwg_python_wrap.c libdwg_python.i

      - name: Compile Python bindings
        run: |
          gcc -fPIC -I/usr/include/python3.9 -c libdwg_python_wrap.c
          gcc -shared libdwg_python_wrap.o -o _libdwg.so -ldwg

      - name: Test Python bindings
        run: |
          python3 -c "import libdwg; print('LibreDWG Python bindings compiled successfully')"

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libdwg-python-bindings
          path: _libdwg.so
